<?php
/**
 * При активации плагина функция создаст таблицы 
 * для комментариев в базах данных MySQL и PostgreSQL.
 */

function create_tables_on_activation() {
    create_table_in_mysql();
    create_table_in_postgresql();
}


function create_table_in_mysql() {

    $table_name = get_table_name();
    $conn = pdo_connect_mysql();

    $sql = "CREATE TABLE IF NOT EXISTS $table_name (
        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100) NOT NULL,
        comment TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ) ENGINE=InnoDB";

    try {
        $conn->exec($sql);
        $conn = null;
        return true;
    } catch (PDOException $e) {
        error_log("SQL Error in create_table_in_mysql(): " . $e->getMessage());
        $conn = null;
        return false;
    }
}


function create_table_in_postgresql() {
    $table_name = get_table_name();
    $conn = pdo_connect_postgresql();

    $sql = "CREATE TABLE IF NOT EXISTS $table_name (
        id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        name VARSHAR (100) NOT NULL,
        comment TEXT NOT NULL,
        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)";

    try {
        $conn->exec($sql);
        $conn = null;
        return true;
    } catch (PDOException $e) {
        error_log("SQL Error in create_table_in_postgresql(): " . $e->getMessage());
        $conn = null;
        return false;
    }
}