<?php

function create_table_in_postgresql() {
    $pg = new PG_DB_Handler();

    $sql = "
        CREATE TABLE IF NOT EXISTS ". TABLE_NAME ." (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(100) NOT NULL,
            comment TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ";

    $result = $pg->query($sql);
    $pg->close();

    if (!$result) {
        error_log('Failed to create PostgreSQL table ' . TABLE_NAME);
    }
}
