<?php

function create_table_in_postgresql() {
    $table_name = get_table_name();
    $conn = pdo_connect_postgresql();
    $sql = "
        CREATE TABLE IF NOT EXISTS $table_name (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(100) NOT NULL,
            comment TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ";

    try {
        $conn->exec($sql);
        $conn = null;
        return true;
    } catch (PDOException $e) {
        error_log("SQL Error in create_table_in_postgresql2: " . $e->getMessage());
        $conn = null;
        return false;
    }
}

function create_table_in_postgresql_old() {
    $pg = new PG_DB_Handler();

    $sql = "
        CREATE TABLE IF NOT EXISTS ". TABLE_NAME ." (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            name VARCHAR(100) NOT NULL,
            comment TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        );
    ";

    $result = $pg->query($sql);
    $pg->close();

    if (!$result) {
        error_log('Failed to create PostgreSQL table ' . TABLE_NAME);
    }
}
